---
abstract: unknown
author:
  - 'Erik Aronesty <earonesty@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-IlluminaSAV
no_index:
  directory:
    - t
    - inc
requires:
  Test::Deep: 0
  Test::Simple: 0
  XML::LibXML::Reader: 0
version: v1.0.7014
